[project]
name = "webvtt-loc"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "alive-progress>=3.3.0",
    "argparse>=1.4.0",
    "structlog>=25.5.0",
    "webvtt-py>=0.5.1",
]

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "pytest>=8.4.2",
    "ruff>=0.14.3",
]
